config/routes.rb
Tidbit::Application.routes.draw do
  get "users/index"

  namespace :admin do
    resources :users
  end
  resources :roles

  devise_for :users, :controllers => {sessions: 'user/sessions',registrations: 'user/registrations',
                          passwords: 'user/passwords'}

  
  get "/home/index"
  post "/home/index"
  get "/home/backbone_view"
  resources :todos
  

  root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  	respond_to do |format|
	    format.html  # index.html.erb
	    format.json  #{ render :json => "{'name':'Tidbit'}" }
	  end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/backbone_view.html.erb
 <style>
div {
	/* jQuery.animate require position */
	position:relative;
	background-color:#abc;
	left:50px;
	width:90px;
	height:90px;
	margin:5px;
}
</style>

<script>
$(document).ready( function(){
	var ItemView = Backbone.View.extend({
	  tagName: 'li'
	});
	
	var BodyView = Backbone.View.extend({
	  el: 'body'
	});
	
	var item = new ItemView();
	var body = new BodyView();
	
	console.log(item.el);
	console.log(body.el);	
	
	$("#right").click(function(){
		$("div").animate({left:"+=40"}, 300);
		$("div").animate({left: "-=40"}, 300);
		$("#userapp").animate({left: "+=40"}, 300);
		$("#userapp").animate({left: "-=40"}, 300);
		console.log("...animate...")
	});
	
});

</script>
  <button id="left">&laquo;</button> <button id="right">&raquo;</button>
  
<div ><h2 id="userapp">Hello, Shake Me</h2></div>

app/views/home/index.html.erb
<ul class="hmenu">
  <%= render 'devise/menu/registration_items' %>
  <%= render 'devise/menu/login_items' %>
  <li><a href="#toggle-userapp" id="toggle-userapp">Login</a></li>
</ul>		

<div id="userapp">
  <h2>Backbone Devise</h2>
  <em>Sample Backbone.js and Devise authorization integration</em>
  <div id="user-tabs">
    <ul class="nav nav-tabs">
      <li class="active"><a href="#login-view" data-toggle="tab" id="login">Login</a></li>
      <li><a href="#signup-view" data-toggle="tab" id="signup">Sign up</a></li>
      <li><a href="#password-view" data-toggle="tab" id="forgotPassword">Forgot password</a></li>
    </ul>
	  <div class="tab-content" id="tab-content">
		<p id="notice"><%= notice %></p>
	  	<div id="login-view"></div>
		<div id="signup-view"></div>
		<div id="password-view"></div>
	  </div>
  </div>

</div>

<!-- I18N -->
<script type="text/javascript">
	//Usage: I18N["login_failed"]
	var I18N = window.I18N = {
		"login_failed": "로그인 실패했습니다.",
		"signed_up_failed": "사용자 등록이 실패했습니다.",
		"signed_up": "사용자가 등록되었습니다.",
		"sending_reset_password_instructions": "패스워드 초기화 안내 메일이 발송되어씁니다.",
		"sending_reset_password_failed": "패스워드 초기화 안내 메일 발송이 실패했습니다. 다시 시도하세요!"
	};
	
</script>


<!-- Template -->
<script type="text/template" id="login-template">
	<%= form_for(resource, :as => resource_name, :url => session_path(resource_name),
					:html => {:id => "sign_in_user"},:format => :json, :remote => true) do |f| %>
	  <div><%= f.label :email %><br />
	  <%= f.email_field :email, :autofocus => true %></div>
	
	  <div><%= f.label :password %><br />
	  <%= f.password_field :password %></div>
	
	  <% if devise_mapping.rememberable? -%>
	    <div><%= f.check_box :remember_me %> <%= f.label :remember_me %></div>
	  <% end -%>
	
	  <div><%= f.submit "Sign in" %></div>
	<% end %>

</script>

<script type="text/template" id="signup-template">
	<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name),
					:html => {:id => "sign_up_user"}, :format => :json, :remote => true) do |f| %>
	  <%= devise_error_messages! %>
	  <div><%= f.label :email %><br />
	  <%= f.email_field :email, :autofocus => true %></div>
	
	  <div><%= f.label :password %><br />
	  <%= f.password_field :password %></div>
	
	  <div><%= f.label :password_confirmation %><br />
	  <%= f.password_field :password_confirmation %></div>
	
	  <div><%= f.submit "Sign up" %></div>
	<% end %>

</script>

<script type="text/template" id="password-template">
	<h2>Forgot your password?</h2>
	<%= form_for(resource, :as => resource_name,  :url => password_path(resource_name),
			:html => { :id =>'password_user', :format =>:json,:remote => true }) do |f| %>
	  <%= devise_error_messages! %>
	
	  <div><%= f.label :email %><br />
	  <%= f.email_field :email, :autofocus => true %></div>
	
	  <div><%= f.submit "Send me reset password instructions" %></div>
	<% end %>
	
</script>

<script type="text/javascript">
	$("#toggle-userapp").click(function(){
		$("#userapp").fadeToggle("slow", "linear");
	});
	//$("#user-tabs").tabs();
</script>