config/routes.rb
Tidbit::Application.routes.draw do
  get "users/index"

  namespace :admin do
    resources :users
  end
  resources :roles

  devise_for :users, :controllers => {sessions: 'user/sessions',registrations: 'user/registrations',
                          passwords: 'user/passwords'}

  
  get "/home/index"
  post "/home/index"
  get "/home/backbone_view"
  resources :todos
  

  root :to => 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :role_ids

  # has and belong to 
  has_many :assignments
  has_many :roles, :through => :assignments
  
  def has_role?(role_sym)
    roles.any? { |r| r.name.underscore.to_sym == role_sym }
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  # GET /admin/users
  # GET /admin/users.json
  def index
    @admin_users = User.page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admin_users }
    end
  end

  # GET /admin/users/1
  # GET /admin/users/1.json
  def show
    @admin_user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @admin_user }
    end
  end

  # GET /admin/users/new
  # GET /admin/users/new.json
  def new
    @admin_user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin_user }
    end
  end

  # GET /admin/users/1/edit
  def edit
    @admin_user = User.find(params[:id])
  end

  # POST /admin/users
  # POST /admin/users.json
  def create
    @admin_user = User.new(params[:user])

    respond_to do |format|
      if @admin_user.save
        format.html { redirect_to admin_user_path( @admin_user), notice: 'User was successfully created.' }
        format.json { render json: @admin_user, status: :created, location: @admin_user }
      else
        format.html { render action: "new" }
        format.json { render json: @admin_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/users/1
  # PUT /admin/users/1.json
  def update
    @admin_user = User.find(params[:id])
    if params[:user][:password].blank?
      params[:user].delete("password")
      params[:user].delete("password_confirmation")
    end
    
    respond_to do |format|
      if @admin_user.update_attributes(params[:user])
        format.html { redirect_to admin_user_path(@admin_user), notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/users/1
  # DELETE /admin/users/1.json
  def destroy
    @admin_user = User.find(params[:id])
    @admin_user.destroy

    respond_to do |format|
      format.html { redirect_to admin_users_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/user/passwords_controller.rb
class User::PasswordsController < Devise::PasswordsController
  # POST /resource/password
  def create
    self.resource = resource_class.send_reset_password_instructions(resource_params)

    if successfully_sent?(resource)
      #respond_with({}, :location => after_sending_reset_password_instructions_path_for(resource_name))
      return render :json => {success: true, notice: "sending_reset_password_instructions"}
    else
      #respond_with(resource)
      return render :json => {success: false, notice: "sending_reset_password_failed"}
    end
  end

end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
  def create
    build_resource
    
    if resource.save
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_navigational_format?
        sign_up(resource_name, resource)
        # respond_with resource, :location => after_sign_up_path_for(resource)
        return render :json => {:success => true, :notice =>"signed_up"}
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_navigational_format?
        expire_session_data_after_sign_in!
        # respond_with resource, :location => after_inactive_sign_up_path_for(resource)
        return render :json => {:success => true, :notice => "signed_up_but_#{resource.inactive_message}"}
      end
    else
      clean_up_passwords resource
      # respond_with resource
      return render :json => {:success => false, :notice =>'signed_up_failed'}
    end
  end
 
  # Signs in a user on sign up. You can overwrite this method in your own
  # RegistrationsController.
  def sign_up(resource_name, resource)
    sign_in(resource_name, resource)
  end
end

app/controllers/user/sessions_controller.rb
class User::SessionsController < Devise::SessionsController
  def create
    p params[:email]
    resource = warden.authenticate!(:scope => resource_name, :recall => "#{controller_path}#failure")
    return sign_in_and_redirect(resource_name, resource)
  end
  
  def sign_in_and_redirect(resource_or_scope, resource=nil)
    scope = Devise::Mapping.find_scope!(resource_or_scope)
    resource ||= resource_or_scope
    sign_in(scope, resource) unless warden.user(scope) == resource
    return render(:json => {:success => true, :redirect => stored_location_for(scope) || after_sign_in_path_for(resource)})
  end
 
  def failure
    return render(:json => {:success => false, :errors => ["login_failed"]})
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user/passwords_helper.rb
module User::PasswordsHelper
end

app/helpers/user/registrations_helper.rb
module User::RegistrationsHelper
end

app/helpers/user/sessions_helper.rb
module User::SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for([:admin,@admin_user]) do |f| %>
  <% if @admin_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_user.errors.count, "error") %> prohibited this admin_user from being saved:</h2>

      <ul>
      <% @admin_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div><%= f.label :email %><br />
  <%= f.email_field :email, :autofocus => true %></div>
  <div><%= f.label :password %><br />
  <%= f.password_field :password %></div>

  <div><%= f.label :role %><br/>
	<% for role in Role.all %>
	<div>
	  <%= check_box_tag "user[role_ids][]", role.id, @admin_user.roles.include?(role) %>
	  <%=h role.name %>
	</div>
	<% end %>
	<%= hidden_field_tag "user[role_ids][]", "" %>
  </div>
	
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Editing admin_user</h1>

<%#= render 'form' %>
<%= form_for([:admin,@admin_user]) do |f| %>
  <% if @admin_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_user.errors.count, "error") %> prohibited this admin_user from being saved:</h2>

      <ul>
      <% @admin_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div><%= f.label :email %><br />
  <%= f.email_field :email, :autofocus => true %></div>

  <div><%= f.label :role %><br/>
	<% for role in Role.all %>
	<div>
	  <%= check_box_tag "user[role_ids][]", role.id, @admin_user.roles.include?(role) %>
	  <%=h role.name %>
	</div>
	<% end %>
	<%= hidden_field_tag "user[role_ids][]", "" %>
  </div>
  <div><%= f.label :password %><br />
  <%= f.password_field :password %></div>
	
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%= link_to 'Show', admin_user_path(@admin_user) %> |
<%= link_to 'Back', admin_users_path %>

app/views/admin/users/index.html.erb
<h1>Listing admin_users</h1>

<table>
  <tr>
  	<th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @admin_users.each do |admin_user| %>
  <tr>
  	<td><%= admin_user.email %></td>
    <td><%= link_to 'Show', admin_user_path(admin_user) %></td>
    <td><%= link_to 'Edit', edit_admin_user_path(admin_user) %></td>
    <td><%= link_to 'Destroy', admin_user_path(admin_user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_admin_user_path %>

app/views/admin/users/new.html.erb
<h1>New admin_user</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_users_path %>

app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>

	<div>Email<br/>
		<%= @admin_user.email %></div>
  <div>Role<br/>
	<% for role in Role.all %>
	<div>
	  <%= check_box_tag "user[role_ids][]", role.id, @admin_user.roles.include?(role), :disabled =>true %>
	  <%=h role.name %>
	</div>
	<% end %>
	<%#= hidden_field_tag "user[role_ids][]", "" %>
  </div>

<%= link_to 'Edit', edit_admin_user_path(@admin_user) %> |
<%= link_to 'Back', admin_users_path %>